### ISSUE TITLE
Can't control GPIO 18 - Getting error

### ISSUE THREAD

**Issue by 2231puppy** [Skiepp/GCodeSuperLaserController#4]
This error is in my octoprint.log:
```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3435, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GSLC/__init__.py", line 34, in hook_gcode_queuing
    commandValue = self.regS.findall(cmd)[0]
IndexError: list index out of range
```

When I run M3 255. Nothing happens with the GPIO pin. OctoPrint version 1.4.2, OctoPi version 0.17.0

**Comment by martinzosr** [comment]
Hello, I had the same problem. After going over the codes, I think the correct format for the command is M3 **S**255.
